### ISSUE TITLE
[Retail] You are trying to skin a button that not exist

### ISSUE THREAD

**Issue by AngelosNaoumis** [sfmict/MountsJournal-ElvUI-Skin#1]
ElvUI ignores the error, but skinning addons (e.g. ElvUI WindTools) is not.

Error:

12x ElvUI_WindTools/Modules/Skins/Widgets/Tab.lua:68: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceHook-3.0-9/AceHook-3.0.lua"]:210: in function <...lvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@ElvUI_Libraries/Core/Ace3/AceHook-3.0-9/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@ElvUI_WindTools/Modules/Skins/Widgets/Tab.lua"]:68: in function <ElvUI_WindTools/Modules/Skins/Widgets/Tab.lua:13>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `HandleTab'
[string "@MountsJournal_ElvUI_Skin/MountsJournal_ElvUI_Skin.lua"]:401: in function <...ountsJournal_ElvUI_Skin/MountsJournal_ElvUI_Skin.lua:276>
[string "=[C]"]: in function `init'
[string "@MountsJournal/Journal.lua"]:1154: in function <MountsJournal/Journal.lua:1148>
[string "=[C]"]: in function `Show'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:483: in function `SetUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:326: in function `ShowUIPanel'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:169: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:164>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:874: in function `ShowUIPanel'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:1048: in function `SetCollectionsJournalShown'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:1034: in function <...rfaceBlizzard_UIParent/Mainline/UIParent.lua:1024>
[string "=[C]"]: ?
[string "=[C]"]: in function `ToggleCollectionsJournal'
[string "@ElvUI_mMediaTag/modules/dock/mCollectionsJournal.lua"]:101: in function `onClick'
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:439: in function <...ceElvUI/Core/Modules/DataTexts/DataTexts.lua:437>

Locals:
(*temporary) = "Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target"

**Comment by sfmict** [comment]
Hi, It's a WindTools bug not MountsJournal-ElvUI-Skin
