### ISSUE TITLE
HandleTab being misused causes errors in ElvUI plugins

### ISSUE THREAD

**Issue by eltreum0** [sfmict/MountsJournal-ElvUI-Skin#3]
As mentioned on the PR, the proper use of the HandleTab from Skins module of ElvUI is to send the parent tab into the function, which will then skin its children

But right now the .selected element of the tab is being sent instead, this causes other addons and plugins to throw errors because the .selected element is not the actual tab and lacks the OnClick function, if you swap to HandleTab(tab) the error will stop and the tab will be properly skinned by ElvUI

**Comment by sfmict** [comment]
This is not a default tab, so I created the style myself. If you want something different, you can do it yourself. HandleTab don't touch OnClick.

**Comment by sfmict** [comment]
HandleTab has been removed :)
